apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paymybuddy-pvc
  labels:
    app: paymybuddy
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
