apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: bd
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres123
  POSTGRES_DB: postgres
  PGADMIN_DEFAULT_EMAIL: admin@local.dev
  PGADMIN_DEFAULT_PASSWORD: admin123
