# apiVersion: v1
# kind: Pod
# metadata:
#   name: mysql-pv
# spec:
#   containers:
#   - image: mysql
#     name: mysql
#     volumeMounts:
#     - mountPath: /var/lib/mysql
#       name: mysql-data
#     env:
#       - name: MYSQL_ROOT_PASSWORD
#         value: password
#       - name: MYSQL_DATABASE
#         value: eazytraining
#       - name: MYSQL_USER
#         value: eazy
#       - name: MYSQL_PASSWORD
#         value: eazy
#   volumes:
#   - name: mysql-data
#     persistentVolumeClaim:
#       claimName: pvc

apiVersion: v1
kind: Pod
metadata:
  name: mysql-pv
spec:
  containers:
  - name: mysql
    image: mysql:8.0
    env:
    - name: MYSQL_DATABASE
      value: eazytraining
    - name: MYSQL_USER
      value: eazy
    - name: MYSQL_PASSWORD
      value: eazy
    - name: MYSQL_ROOT_PASSWORD
      value: password
    ports:
    - containerPort: 3306
    volumeMounts:
    - name: mysql-persistent-storage
      mountPath: /var/lib/mysql
  volumes:
  - name: mysql-persistent-storage
    persistentVolumeClaim:
      claimName: mysql-pvc